PACKAGE_NAME="focaltech-ft8722"
PACKAGE_VERSION="0.1.2"
BUILT_MODULE_NAME[0]="ft8722_ts"
DEST_MODULE_LOCATION[0]="/updates/extra"
AUTOINSTALL="yes"

MAKE[0]="make KERNELRELEASE=${kernelver}"
CLEAN="make clean KERNELRELEASE=${kernelver}"
