PACKAGE_NAME="t6-platform"
PACKAGE_VERSION="0.9.13"
BUILT_MODULE_NAME[0]="t6_platform"
DEST_MODULE_LOCATION[0]="/updates/extra"
AUTOINSTALL="yes"

MAKE[0]="make KERNELRELEASE=${kernelver}"
CLEAN="make clean KERNELRELEASE=${kernelver}"
