PACKAGE_NAME="ite-it6616"
PACKAGE_VERSION="0.1.1"
BUILT_MODULE_NAME[0]="ite_it6616"
DEST_MODULE_LOCATION[0]="/updates/extra"
AUTOINSTALL="yes"

MAKE[0]="make KERNELRELEASE=${kernelver}"
CLEAN="make clean KERNELRELEASE=${kernelver}"
