# Keyboard / remote control. Touch goes through uosc.
LEFT        seek -10
RIGHT       seek 10
UP          add volume 5
DOWN        add volume -5
ENTER       cycle pause
KP_ENTER    cycle pause
SPACE       cycle pause
PLAYPAUSE   cycle pause
VOLUME_UP   add volume 5
VOLUME_DOWN add volume -5
MUTE        cycle mute
ESC         quit
BS          quit
